### ISSUE TITLE
how to install Coco from release on mac

### ISSUE THREAD

**Issue by SyMind** [inherd/coco#87]
I don't know how to install it on mac. Should I use `coco_macos`? I don't know how to do it.

**Comment by phodal** [comment]
download from `https://github.com/inherd/coca/releases`, and use `coco_macos`

**Comment by daolou** [comment]
![image](https://user-images.githubusercontent.com/22312092/123222096-2c9bf000-d502-11eb-9d47-0bb5ee588db6.png)

环境：
macos: bigsur 11.3

**Comment by phodal** [comment]
需要在 Terminal 里运行

**Comment by daolou** [comment]
> 需要在 Terminal 里运行

咋运行啊，看上去是个 二进制文件，直接拖到 Terminal ？

**Comment by daolou** [comment]
知道咋用了，mac 下载到 downloads 目录下，只有 rw 的权限，导致看不出来是个 exec 文件

**Comment by phodal** [comment]
@daolou 来个 PR 说明一下 ？

**Comment by daolou** [comment]
> @daolou 来个 PR 说明一下 ？

好的
