### ISSUE TITLE
Failed: CocoError: cause by: unzip error

### ISSUE THREAD

**Issue by rc452860** [inherd/coco#96]
### Steps to reproduce (please include code)
 ./coco_linux.coco_linux plugins
create plugins dir success
download from https://github.com/inherd/coco/releases/download/v0.5.4/coco_plugins_linux.zip
Failed: CocoError: cause by: unzip error

### Environment
- coco version 0.5.4
- Rust version unknow
- OS: [e.g. Linux]

**Comment by phodal** [comment]
之前，发布错了版本，我发布一个新的吧

**Comment by rc452860** [comment]
还有个问题，这几个插件是干嘛用的，文档没看到介绍。

**Comment by phodal** [comment]
晚点我补充一下文档：

 - coco_container，容器化分析
 - coco_pipeline，流水线分析
 - coco_struct，模型分析
 - coco_swagger，Swagger API 分析

**Comment by phodal** [comment]
fixed #https://github.com/inherd/coco/commit/ebbd054f1717fa80d4461fa16316e47c4c3890de
